config/routes.rb
# @authors: Iskandar Suhaimi
# @email: hello@iskandarsuhaimi.com 

Rails.application.routes.draw do
  post '/' => 'chat_controller#run', as: "receive_webhooks"
  resources :question_lists, only: [:new, :create], :path => 'question'
end

app/models/question_list.rb
class QuestionList < ApplicationRecord
  validates :question, uniqueness: true
end

app/controllers/question_lists_controller.rb
class QuestionListsController < ApplicationController
  before_action :set_question_list, only: [:show, :edit, :update, :destroy]

  # GET /question_lists
  # GET /question_lists.json
  def index
    @question_lists = QuestionList.all
  end

  # GET /question_lists/1
  # GET /question_lists/1.json
  def show
  end

  # GET /question_lists/new
  def new
    @question_list = QuestionList.new
  end

  # GET /question_lists/1/edit
  def edit
  end

  # POST /question_lists
  # POST /question_lists.json
  def create
    answers = params[:question_list][:answer].reject { |a| a.empty? }.uniq
    if answers.empty? or params[:question_list][:question].blank?
      render plain: "Question and Answers can't be empty", status: :unprocessable_entity
    else
      question = QuestionList.create(question: params[:question_list][:question], answer: answers)
      render plain: question.errors.full_messages[0] || "Question has been submitted to be approved", status: :ok
    end
    # @question_list = QuestionList.new(question_list_params)
    #
    # respond_to do |format|
    #   if @question_list.save
    #     format.html { redirect_to @question_list, notice: 'Question list was successfully created.' }
    #     format.json { render :show, status: :created, location: @question_list }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @question_list.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /question_lists/1
  # PATCH/PUT /question_lists/1.json
  def update
    respond_to do |format|
      if @question_list.update(question_list_params)
        format.html { redirect_to @question_list, notice: 'Question list was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_list }
      else
        format.html { render :edit }
        format.json { render json: @question_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_lists/1
  # DELETE /question_lists/1.json
  def destroy
    @question_list.destroy
    respond_to do |format|
      format.html { redirect_to question_lists_url, notice: 'Question list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_list
      @question_list = QuestionList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_list_params
      params.require(:question_list).permit(:question, :enabled, :answer => [])
    end
end

app/helpers/question_lists_helper.rb
module QuestionListsHelper
end

app/views/question_lists/_form.html.erb
<%= form_with(model: question_list, local: true) do |form| %>
  <% if question_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question_list.errors.count, "error") %> prohibited this question from being submitted:</h2>

      <ul>
      <% question_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question, :required => true %>
  </div>
<br>
    <%= form.label :answers, "Answers (minimum 1)" %>
  <%
    i = 1
    10.times do
  %>
  <div class="field" style="margin-top: 5px" >
    <%= i.to_s+". "%>
    <%= form.text_field :answer, name: "question_list[answer][]"%>
    <% i += 1 %>
  </div>
  <% end %>

<!--  <div class="field">-->
    <%#= form.label :enabled %>
    <%#= form.text_field :enabled %>
<!--  </div>-->

  <br>
  <div class="actions">
    <%= form.submit "Submit" %>
  </div>
<% end %>

app/views/question_lists/edit.html.erb
<h1>Editing Question List</h1>

<%= render 'form', question_list: @question_list %>

<%= link_to 'Show', @question_list %> |
<%= link_to 'Back', question_lists_path %>

app/views/question_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Question Lists</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th>Enabled</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_lists.each do |question_list| %>
      <tr>
        <td><%= question_list.question %></td>
        <td><%= question_list.answer %></td>
        <td><%= question_list.enabled %></td>
        <td><%= link_to 'Show', question_list %></td>
        <td><%= link_to 'Edit', edit_question_list_path(question_list) %></td>
        <td><%= link_to 'Destroy', question_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question List', new_question_list_path %>

app/views/question_lists/new.html.erb
<h1>New Question</h1>

<%= render 'form', question_list: @question_list %>

<%#= link_to 'Back', question_lists_path %>

app/views/question_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question_list.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question_list.answer %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @question_list.enabled %>
</p>

<%= link_to 'Edit', edit_question_list_path(@question_list) %> |
<%= link_to 'Back', question_lists_path %>